### GET request to example server
POST {{baseUrl}}/product/create
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "test product created created",
  "price": {
    "amount": 20000,
    "currency": "COP"
  },
  "description": "test description",
  "stock": 1
}

###
